"""empty message

Revision ID: 072d0dfc0f88
Revises: 
Create Date: 2025-03-17 18:25:57.008176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072d0dfc0f88'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_from',
    sa.Column('from_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('clientfrom', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('from_id'),
    sa.UniqueConstraint('from_id')
    )
    op.create_table('client_status',
    sa.Column('status_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('status_id')
    )
    op.create_table('client',
    sa.Column('client_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=255), nullable=False),
    sa.Column('service', sa.VARCHAR(length=255), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.Column('client_from', sa.BigInteger(), nullable=False),
    sa.Column('client_status', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_from'], ['client_from.from_id'], ),
    sa.ForeignKeyConstraint(['client_status'], ['client_status.status_id'], ),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    op.drop_table('client_status')
    op.drop_table('client_from')
    # ### end Alembic commands ###
