"""Initial migration

Revision ID: 8d844a58b893
Revises: 
Create Date: 2025-03-16 10:54:48.754680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d844a58b893'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=255), nullable=False),
    sa.Column('service', sa.VARCHAR(length=255), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.Column('client_from', sa.VARCHAR(length=255), nullable=False),
    sa.Column('client_status', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
